-- Auto-generated by tool/generate_seed_listings.dart — do not edit by hand
-- Inserts published demo listings when a owner/agent profile exists.

DO $$
DECLARE
  owner_uid uuid;
  listing_uid uuid;
  seq int := 1;
  proj record;
  u int;
  is_rent boolean;
  price numeric;
  lat double precision;
  lng double precision;
  bed int;
  area numeric;
  title text;
  slug text;
BEGIN
  SELECT id INTO owner_uid FROM public.profiles
  WHERE role IN ('owner', 'agent', 'admin')
  ORDER BY created_at
  LIMIT 1;

  IF owner_uid IS NULL THEN
    RAISE NOTICE 'seed_listings: skipped — create a user with role owner/agent first';
    RETURN;
  END IF;

  IF EXISTS (SELECT 1 FROM public.listings WHERE listing_code LIKE 'LB-SEED-%' LIMIT 1) THEN
    RAISE NOTICE 'seed_listings: already present';
    RETURN;
  END IF;

  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-0001',
    owner_uid, owner_uid,
    'rent',
    'published', 'condo',
    '1 นอน · ทรู ทองหล่อ',
    45791,
    1, 1, 56,
    'วัฒนา',
    'ทรู ทองหล่อ',
    false,
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint(100.57938396543956, 13.724846724063148), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/true-thonglor-0-a', 'https://picsum.photos/seed/true-thonglor-0-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/true-thonglor-0-b', 'https://picsum.photos/seed/true-thonglor-0-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/true-thonglor-0-c', 'https://picsum.photos/seed/true-thonglor-0-c/800/600', 2, 'approved');

  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-0002',
    owner_uid, owner_uid,
    'rent',
    'published', 'condo',
    '2 นอน · ทรู ทองหล่อ',
    42933,
    2, 1, 47,
    'วัฒนา',
    'ทรู ทองหล่อ',
    false,
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint(100.5795788627736, 13.725784245330269), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/true-thonglor-1-a', 'https://picsum.photos/seed/true-thonglor-1-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/true-thonglor-1-b', 'https://picsum.photos/seed/true-thonglor-1-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/true-thonglor-1-c', 'https://picsum.photos/seed/true-thonglor-1-c/800/600', 2, 'approved');

  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-0003',
    owner_uid, owner_uid,
    'rent',
    'published', 'condo',
    'สตูดิโอ · ทรู ทองหล่อ',
    51283,
    0, 1, 28,
    'วัฒนา',
    'ทรู ทองหล่อ',
    true,
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint(100.5806870365419, 13.722677316789747), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/true-thonglor-2-a', 'https://picsum.photos/seed/true-thonglor-2-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/true-thonglor-2-b', 'https://picsum.photos/seed/true-thonglor-2-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/true-thonglor-2-c', 'https://picsum.photos/seed/true-thonglor-2-c/800/600', 2, 'approved');

  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-0004',
    owner_uid, owner_uid,
    'rent',
    'published', 'condo',
    '2 นอน · โนเบิล รีมิกซ์ ทองหล่อ',
    62136,
    2, 1, 55,
    'วัฒนา',
    'โนเบิล รีมิกซ์ ทองหล่อ',
    true,
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint(100.58390037250153, 13.727623711621735), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/noble-remix-thonglor-0-a', 'https://picsum.photos/seed/noble-remix-thonglor-0-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/noble-remix-thonglor-0-b', 'https://picsum.photos/seed/noble-remix-thonglor-0-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/noble-remix-thonglor-0-c', 'https://picsum.photos/seed/noble-remix-thonglor-0-c/800/600', 2, 'approved');

  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-0005',
    owner_uid, owner_uid,
    'rent',
    'published', 'condo',
    '2 นอน · โนเบิล รีมิกซ์ ทองหล่อ',
    48204,
    2, 1, 38,
    'วัฒนา',
    'โนเบิล รีมิกซ์ ทองหล่อ',
    false,
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint(100.58243311554105, 13.724953112110622), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/noble-remix-thonglor-1-a', 'https://picsum.photos/seed/noble-remix-thonglor-1-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/noble-remix-thonglor-1-b', 'https://picsum.photos/seed/noble-remix-thonglor-1-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/noble-remix-thonglor-1-c', 'https://picsum.photos/seed/noble-remix-thonglor-1-c/800/600', 2, 'approved');

  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-0006',
    owner_uid, owner_uid,
    'rent',
    'published', 'condo',
    '2 นอน · แอสตัน อโศก',
    27681,
    2, 1, 38,
    'วัฒนา',
    'แอสตัน อโศก',
    true,
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint(100.5625764803406, 13.738053766169648), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/ashton-asoke-0-a', 'https://picsum.photos/seed/ashton-asoke-0-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/ashton-asoke-0-b', 'https://picsum.photos/seed/ashton-asoke-0-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/ashton-asoke-0-c', 'https://picsum.photos/seed/ashton-asoke-0-c/800/600', 2, 'approved');

  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-0007',
    owner_uid, owner_uid,
    'rent',
    'published', 'condo',
    '2 นอน · แอสตัน อโศก',
    26095,
    2, 1, 46,
    'วัฒนา',
    'แอสตัน อโศก',
    false,
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint(100.56419841560407, 13.738172541558873), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/ashton-asoke-1-a', 'https://picsum.photos/seed/ashton-asoke-1-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/ashton-asoke-1-b', 'https://picsum.photos/seed/ashton-asoke-1-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/ashton-asoke-1-c', 'https://picsum.photos/seed/ashton-asoke-1-c/800/600', 2, 'approved');

  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-0008',
    owner_uid, owner_uid,
    'sale',
    'published', 'condo',
    'แอสตัน อโศก ขาย',
    13172244,
    0, 1, 45,
    'วัฒนา',
    'แอสตัน อโศก',
    false,
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint(100.56230738121792, 13.740867164824804), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/ashton-asoke-2-a', 'https://picsum.photos/seed/ashton-asoke-2-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/ashton-asoke-2-b', 'https://picsum.photos/seed/ashton-asoke-2-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/ashton-asoke-2-c', 'https://picsum.photos/seed/ashton-asoke-2-c/800/600', 2, 'approved');

  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-0009',
    owner_uid, owner_uid,
    'sale',
    'published', 'condo',
    'ริธึม สุขุมวิท 36 ขาย',
    15090020,
    2, 1, 43,
    'คลองเตย',
    'ริธึม สุขุมวิท 36',
    false,
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint(100.56943367196814, 13.733934933495197), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/rhythm-sukhumvit-36-0-a', 'https://picsum.photos/seed/rhythm-sukhumvit-36-0-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/rhythm-sukhumvit-36-0-b', 'https://picsum.photos/seed/rhythm-sukhumvit-36-0-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/rhythm-sukhumvit-36-0-c', 'https://picsum.photos/seed/rhythm-sukhumvit-36-0-c/800/600', 2, 'approved');

  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-0010',
    owner_uid, owner_uid,
    'rent',
    'published', 'condo',
    'สตูดิโอ · ริธึม สุขุมวิท 36',
    58174,
    0, 1, 29,
    'คลองเตย',
    'ริธึม สุขุมวิท 36',
    false,
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint(100.57165960028559, 13.737332873887791), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/rhythm-sukhumvit-36-1-a', 'https://picsum.photos/seed/rhythm-sukhumvit-36-1-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/rhythm-sukhumvit-36-1-b', 'https://picsum.photos/seed/rhythm-sukhumvit-36-1-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/rhythm-sukhumvit-36-1-c', 'https://picsum.photos/seed/rhythm-sukhumvit-36-1-c/800/600', 2, 'approved');

  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-0011',
    owner_uid, owner_uid,
    'rent',
    'published', 'condo',
    'สตูดิโอ · ริธึม สุขุมวิท 36',
    62488,
    0, 1, 62,
    'คลองเตย',
    'ริธึม สุขุมวิท 36',
    false,
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint(100.57276815275661, 13.737731064404752), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/rhythm-sukhumvit-36-2-a', 'https://picsum.photos/seed/rhythm-sukhumvit-36-2-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/rhythm-sukhumvit-36-2-b', 'https://picsum.photos/seed/rhythm-sukhumvit-36-2-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/rhythm-sukhumvit-36-2-c', 'https://picsum.photos/seed/rhythm-sukhumvit-36-2-c/800/600', 2, 'approved');

  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-0012',
    owner_uid, owner_uid,
    'rent',
    'published', 'condo',
    'สตูดิโอ · เดอะ ลอฟท์ เอกมัย',
    30238,
    0, 1, 48,
    'วัฒนา',
    'เดอะ ลอฟท์ เอกมัย',
    true,
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint(100.5852364664858, 13.72989777438627), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/the-lofts-ekkamai-0-a', 'https://picsum.photos/seed/the-lofts-ekkamai-0-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/the-lofts-ekkamai-0-b', 'https://picsum.photos/seed/the-lofts-ekkamai-0-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/the-lofts-ekkamai-0-c', 'https://picsum.photos/seed/the-lofts-ekkamai-0-c/800/600', 2, 'approved');

  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-0013',
    owner_uid, owner_uid,
    'rent',
    'published', 'condo',
    '2 นอน · เดอะ ลอฟท์ เอกมัย',
    42560,
    2, 1, 60,
    'วัฒนา',
    'เดอะ ลอฟท์ เอกมัย',
    false,
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint(100.58355367273568, 13.727955814850047), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/the-lofts-ekkamai-1-a', 'https://picsum.photos/seed/the-lofts-ekkamai-1-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/the-lofts-ekkamai-1-b', 'https://picsum.photos/seed/the-lofts-ekkamai-1-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/the-lofts-ekkamai-1-c', 'https://picsum.photos/seed/the-lofts-ekkamai-1-c/800/600', 2, 'approved');

  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-0014',
    owner_uid, owner_uid,
    'rent',
    'published', 'condo',
    '2 นอน · เดอะ ลอฟท์ เอกมัย',
    48060,
    2, 1, 34,
    'วัฒนา',
    'เดอะ ลอฟท์ เอกมัย',
    true,
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint(100.58450520704966, 13.730343226876291), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/the-lofts-ekkamai-2-a', 'https://picsum.photos/seed/the-lofts-ekkamai-2-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/the-lofts-ekkamai-2-b', 'https://picsum.photos/seed/the-lofts-ekkamai-2-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/the-lofts-ekkamai-2-c', 'https://picsum.photos/seed/the-lofts-ekkamai-2-c/800/600', 2, 'approved');

  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-0015',
    owner_uid, owner_uid,
    'rent',
    'published', 'condo',
    'สตูดิโอ · ยู ดีไลท์ บางนา',
    32796,
    0, 1, 49,
    'บางนา',
    'ยู ดีไลท์ บางนา',
    true,
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint(100.60277909585214, 13.667089680408985), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/u-delight-bangna-0-a', 'https://picsum.photos/seed/u-delight-bangna-0-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/u-delight-bangna-0-b', 'https://picsum.photos/seed/u-delight-bangna-0-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/u-delight-bangna-0-c', 'https://picsum.photos/seed/u-delight-bangna-0-c/800/600', 2, 'approved');

  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-0016',
    owner_uid, owner_uid,
    'rent',
    'published', 'condo',
    '1 นอน · ยู ดีไลท์ บางนา',
    31107,
    1, 1, 61,
    'บางนา',
    'ยู ดีไลท์ บางนา',
    false,
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint(100.6060046740218, 13.66690376803058), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/u-delight-bangna-1-a', 'https://picsum.photos/seed/u-delight-bangna-1-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/u-delight-bangna-1-b', 'https://picsum.photos/seed/u-delight-bangna-1-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/u-delight-bangna-1-c', 'https://picsum.photos/seed/u-delight-bangna-1-c/800/600', 2, 'approved');

  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-0017',
    owner_uid, owner_uid,
    'rent',
    'published', 'condo',
    '2 นอน · ไอดีโอ โมบิ สุขุมวิท',
    38798,
    2, 1, 60,
    'พระโขนง',
    'ไอดีโอ โมบิ สุขุมวิท',
    true,
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint(100.60129844479778, 13.701194406771746), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/ideo-mobi-sukhumvit-0-a', 'https://picsum.photos/seed/ideo-mobi-sukhumvit-0-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/ideo-mobi-sukhumvit-0-b', 'https://picsum.photos/seed/ideo-mobi-sukhumvit-0-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/ideo-mobi-sukhumvit-0-c', 'https://picsum.photos/seed/ideo-mobi-sukhumvit-0-c/800/600', 2, 'approved');

  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-0018',
    owner_uid, owner_uid,
    'rent',
    'published', 'condo',
    '2 นอน · ไอดีโอ โมบิ สุขุมวิท',
    19668,
    2, 1, 52,
    'พระโขนง',
    'ไอดีโอ โมบิ สุขุมวิท',
    false,
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint(100.60001790263208, 13.702267431514134), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/ideo-mobi-sukhumvit-1-a', 'https://picsum.photos/seed/ideo-mobi-sukhumvit-1-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/ideo-mobi-sukhumvit-1-b', 'https://picsum.photos/seed/ideo-mobi-sukhumvit-1-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/ideo-mobi-sukhumvit-1-c', 'https://picsum.photos/seed/ideo-mobi-sukhumvit-1-c/800/600', 2, 'approved');

  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-0019',
    owner_uid, owner_uid,
    'sale',
    'published', 'condo',
    'เดอะ คีย์ BTS วุฒากาศ ขาย',
    3064933,
    2, 1, 61,
    'บางบอน',
    'เดอะ คีย์ BTS วุฒากาศ',
    true,
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint(100.45732498442896, 13.711798519294822), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/the-key-bts-wutthakat-0-a', 'https://picsum.photos/seed/the-key-bts-wutthakat-0-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/the-key-bts-wutthakat-0-b', 'https://picsum.photos/seed/the-key-bts-wutthakat-0-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/the-key-bts-wutthakat-0-c', 'https://picsum.photos/seed/the-key-bts-wutthakat-0-c/800/600', 2, 'approved');

  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-0020',
    owner_uid, owner_uid,
    'rent',
    'published', 'condo',
    '1 นอน · เดอะ คีย์ BTS วุฒากาศ',
    34745,
    1, 1, 33,
    'บางบอน',
    'เดอะ คีย์ BTS วุฒากาศ',
    true,
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint(100.45754696014814, 13.712349371880757), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/the-key-bts-wutthakat-1-a', 'https://picsum.photos/seed/the-key-bts-wutthakat-1-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/the-key-bts-wutthakat-1-b', 'https://picsum.photos/seed/the-key-bts-wutthakat-1-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/the-key-bts-wutthakat-1-c', 'https://picsum.photos/seed/the-key-bts-wutthakat-1-c/800/600', 2, 'approved');

  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-0021',
    owner_uid, owner_uid,
    'sale',
    'published', 'condo',
    'ไลฟ์ แอท รามา 9 ขาย',
    13153359,
    1, 1, 50,
    'ห้วยขวาง',
    'ไลฟ์ แอท รามา 9',
    true,
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint(100.56611667662975, 13.757440090711915), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/life-rama-9-0-a', 'https://picsum.photos/seed/life-rama-9-0-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/life-rama-9-0-b', 'https://picsum.photos/seed/life-rama-9-0-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/life-rama-9-0-c', 'https://picsum.photos/seed/life-rama-9-0-c/800/600', 2, 'approved');

  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-0022',
    owner_uid, owner_uid,
    'rent',
    'published', 'condo',
    'สตูดิโอ · ไลฟ์ แอท รามา 9',
    31401,
    0, 1, 42,
    'ห้วยขวาง',
    'ไลฟ์ แอท รามา 9',
    true,
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint(100.56352133813013, 13.758777457169836), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/life-rama-9-1-a', 'https://picsum.photos/seed/life-rama-9-1-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/life-rama-9-1-b', 'https://picsum.photos/seed/life-rama-9-1-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/life-rama-9-1-c', 'https://picsum.photos/seed/life-rama-9-1-c/800/600', 2, 'approved');

  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-0023',
    owner_uid, owner_uid,
    'rent',
    'published', 'condo',
    '1 นอน · ไลฟ์ แอท รามา 9',
    23037,
    1, 1, 37,
    'ห้วยขวาง',
    'ไลฟ์ แอท รามา 9',
    true,
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint(100.56508188202118, 13.75968344864288), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/life-rama-9-2-a', 'https://picsum.photos/seed/life-rama-9-2-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/life-rama-9-2-b', 'https://picsum.photos/seed/life-rama-9-2-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/life-rama-9-2-c', 'https://picsum.photos/seed/life-rama-9-2-c/800/600', 2, 'approved');

  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-0024',
    owner_uid, owner_uid,
    'rent',
    'published', 'condo',
    '1 นอน · แอสไพร์ สาทร',
    44384,
    1, 1, 28,
    'สาทร',
    'แอสไพร์ สาทร',
    true,
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint(100.52806043672584, 13.720325534147001), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/aspire-sathorn-0-a', 'https://picsum.photos/seed/aspire-sathorn-0-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/aspire-sathorn-0-b', 'https://picsum.photos/seed/aspire-sathorn-0-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/aspire-sathorn-0-c', 'https://picsum.photos/seed/aspire-sathorn-0-c/800/600', 2, 'approved');

  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-0025',
    owner_uid, owner_uid,
    'rent',
    'published', 'condo',
    'สตูดิโอ · แอสไพร์ สาทร',
    53819,
    0, 1, 43,
    'สาทร',
    'แอสไพร์ สาทร',
    true,
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint(100.53148291300941, 13.718884421962349), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/aspire-sathorn-1-a', 'https://picsum.photos/seed/aspire-sathorn-1-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/aspire-sathorn-1-b', 'https://picsum.photos/seed/aspire-sathorn-1-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/aspire-sathorn-1-c', 'https://picsum.photos/seed/aspire-sathorn-1-c/800/600', 2, 'approved');

  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-0026',
    owner_uid, owner_uid,
    'rent',
    'published', 'condo',
    '1 นอน · ดิ แอดเดรส สาทร',
    17042,
    1, 1, 55,
    'สาทร',
    'ดิ แอดเดรส สาทร',
    false,
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint(100.53310964305408, 13.719935922056292), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/the-address-sathorn-0-a', 'https://picsum.photos/seed/the-address-sathorn-0-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/the-address-sathorn-0-b', 'https://picsum.photos/seed/the-address-sathorn-0-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/the-address-sathorn-0-c', 'https://picsum.photos/seed/the-address-sathorn-0-c/800/600', 2, 'approved');

  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-0027',
    owner_uid, owner_uid,
    'rent',
    'published', 'condo',
    '2 นอน · ดิ แอดเดรส สาทร',
    50539,
    2, 1, 34,
    'สาทร',
    'ดิ แอดเดรส สาทร',
    true,
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint(100.5323128310703, 13.722895979611424), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/the-address-sathorn-1-a', 'https://picsum.photos/seed/the-address-sathorn-1-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/the-address-sathorn-1-b', 'https://picsum.photos/seed/the-address-sathorn-1-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/the-address-sathorn-1-c', 'https://picsum.photos/seed/the-address-sathorn-1-c/800/600', 2, 'approved');

  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-0028',
    owner_uid, owner_uid,
    'sale',
    'published', 'condo',
    'ลุมพินี เพลส พระราม 3 ขาย',
    7690033,
    1, 1, 60,
    'ยานนาวา',
    'ลุมพินี เพลส พระราม 3',
    false,
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint(100.53805933276769, 13.681832513865153), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/lumpini-place-rama3-0-a', 'https://picsum.photos/seed/lumpini-place-rama3-0-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/lumpini-place-rama3-0-b', 'https://picsum.photos/seed/lumpini-place-rama3-0-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/lumpini-place-rama3-0-c', 'https://picsum.photos/seed/lumpini-place-rama3-0-c/800/600', 2, 'approved');

  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-0029',
    owner_uid, owner_uid,
    'rent',
    'published', 'condo',
    '2 นอน · ลุมพินี เพลส พระราม 3',
    32849,
    2, 1, 38,
    'ยานนาวา',
    'ลุมพินี เพลส พระราม 3',
    true,
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint(100.53833324393116, 13.680674138393876), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/lumpini-place-rama3-1-a', 'https://picsum.photos/seed/lumpini-place-rama3-1-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/lumpini-place-rama3-1-b', 'https://picsum.photos/seed/lumpini-place-rama3-1-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/lumpini-place-rama3-1-c', 'https://picsum.photos/seed/lumpini-place-rama3-1-c/800/600', 2, 'approved');

  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-0030',
    owner_uid, owner_uid,
    'rent',
    'published', 'condo',
    '2 นอน · ลุมพินี เพลส พระราม 3',
    13683,
    2, 1, 30,
    'ยานนาวา',
    'ลุมพินี เพลส พระราม 3',
    true,
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint(100.53726227507187, 13.684457531705712), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/lumpini-place-rama3-2-a', 'https://picsum.photos/seed/lumpini-place-rama3-2-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/lumpini-place-rama3-2-b', 'https://picsum.photos/seed/lumpini-place-rama3-2-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/lumpini-place-rama3-2-c', 'https://picsum.photos/seed/lumpini-place-rama3-2-c/800/600', 2, 'approved');

  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-0031',
    owner_uid, owner_uid,
    'sale',
    'published', 'condo',
    'แมกโนเลียส ราชดำริ ขาย',
    14148505,
    1, 1, 40,
    'ปทุมวัน',
    'แมกโนเลียส ราชดำริ',
    true,
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint(100.5409889470506, 13.74390539771536), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/magnolias-ratchadamri-0-a', 'https://picsum.photos/seed/magnolias-ratchadamri-0-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/magnolias-ratchadamri-0-b', 'https://picsum.photos/seed/magnolias-ratchadamri-0-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/magnolias-ratchadamri-0-c', 'https://picsum.photos/seed/magnolias-ratchadamri-0-c/800/600', 2, 'approved');

  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-0032',
    owner_uid, owner_uid,
    'rent',
    'published', 'condo',
    '1 นอน · แมกโนเลียส ราชดำริ',
    47469,
    1, 1, 44,
    'ปทุมวัน',
    'แมกโนเลียส ราชดำริ',
    true,
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint(100.540906183763, 13.740884343227563), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/magnolias-ratchadamri-1-a', 'https://picsum.photos/seed/magnolias-ratchadamri-1-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/magnolias-ratchadamri-1-b', 'https://picsum.photos/seed/magnolias-ratchadamri-1-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/magnolias-ratchadamri-1-c', 'https://picsum.photos/seed/magnolias-ratchadamri-1-c/800/600', 2, 'approved');

  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-0033',
    owner_uid, owner_uid,
    'rent',
    'published', 'condo',
    '1 นอน · แมกโนเลียส ราชดำริ',
    33913,
    1, 1, 29,
    'ปทุมวัน',
    'แมกโนเลียส ราชดำริ',
    false,
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint(100.53906114438664, 13.743865638286136), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/magnolias-ratchadamri-2-a', 'https://picsum.photos/seed/magnolias-ratchadamri-2-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/magnolias-ratchadamri-2-b', 'https://picsum.photos/seed/magnolias-ratchadamri-2-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/magnolias-ratchadamri-2-c', 'https://picsum.photos/seed/magnolias-ratchadamri-2-c/800/600', 2, 'approved');

  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-0034',
    owner_uid, owner_uid,
    'rent',
    'published', 'condo',
    'สตูดิโอ · เดอะไลน์ สุขุมวิท 101',
    33259,
    0, 1, 34,
    'วัฒนา',
    'เดอะไลน์ สุขุมวิท 101',
    false,
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint(100.60748441123674, 13.69075346629006), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/the-line-sukhumvit-101-0-a', 'https://picsum.photos/seed/the-line-sukhumvit-101-0-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/the-line-sukhumvit-101-0-b', 'https://picsum.photos/seed/the-line-sukhumvit-101-0-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/the-line-sukhumvit-101-0-c', 'https://picsum.photos/seed/the-line-sukhumvit-101-0-c/800/600', 2, 'approved');

  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-0035',
    owner_uid, owner_uid,
    'rent',
    'published', 'condo',
    'สตูดิโอ · เดอะไลน์ สุขุมวิท 101',
    40086,
    0, 1, 41,
    'วัฒนา',
    'เดอะไลน์ สุขุมวิท 101',
    true,
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint(100.60616577357561, 13.688661501548035), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/the-line-sukhumvit-101-1-a', 'https://picsum.photos/seed/the-line-sukhumvit-101-1-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/the-line-sukhumvit-101-1-b', 'https://picsum.photos/seed/the-line-sukhumvit-101-1-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/the-line-sukhumvit-101-1-c', 'https://picsum.photos/seed/the-line-sukhumvit-101-1-c/800/600', 2, 'approved');

  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-0036',
    owner_uid, owner_uid,
    'rent',
    'published', 'condo',
    '2 นอน · เดอะไลน์ สุขุมวิท 101',
    23489,
    2, 1, 28,
    'วัฒนา',
    'เดอะไลน์ สุขุมวิท 101',
    true,
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint(100.60572799582327, 13.688703001732522), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/the-line-sukhumvit-101-2-a', 'https://picsum.photos/seed/the-line-sukhumvit-101-2-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/the-line-sukhumvit-101-2-b', 'https://picsum.photos/seed/the-line-sukhumvit-101-2-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/the-line-sukhumvit-101-2-c', 'https://picsum.photos/seed/the-line-sukhumvit-101-2-c/800/600', 2, 'approved');

  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-0037',
    owner_uid, owner_uid,
    'rent',
    'published', 'condo',
    '2 นอน · พาร์ค ออริจิ้น ทองหล่อ',
    18834,
    2, 1, 53,
    'วัฒนา',
    'พาร์ค ออริจิ้น ทองหล่อ',
    false,
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint(100.5761933183499, 13.733482180099577), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/park-origin-thonglor-0-a', 'https://picsum.photos/seed/park-origin-thonglor-0-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/park-origin-thonglor-0-b', 'https://picsum.photos/seed/park-origin-thonglor-0-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/park-origin-thonglor-0-c', 'https://picsum.photos/seed/park-origin-thonglor-0-c/800/600', 2, 'approved');

  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-0038',
    owner_uid, owner_uid,
    'sale',
    'published', 'condo',
    'พาร์ค ออริจิ้น ทองหล่อ ขาย',
    3772007,
    2, 1, 34,
    'วัฒนา',
    'พาร์ค ออริจิ้น ทองหล่อ',
    false,
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint(100.57755912134131, 13.732142923250082), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/park-origin-thonglor-1-a', 'https://picsum.photos/seed/park-origin-thonglor-1-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/park-origin-thonglor-1-b', 'https://picsum.photos/seed/park-origin-thonglor-1-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/park-origin-thonglor-1-c', 'https://picsum.photos/seed/park-origin-thonglor-1-c/800/600', 2, 'approved');

  RAISE NOTICE 'seed_listings: inserted % listings', 38;
END $$;

