// Generates supabase/seed_listings.sql from Bangkok project data.
// Run: dart run tool/generate_seed_listings.dart

import 'dart:io';
import 'dart:math';

void main() {
  final projects = _projects;
  final rng = Random(42);
  final buf = StringBuffer('''
-- Auto-generated by tool/generate_seed_listings.dart — do not edit by hand
-- Inserts published demo listings when a owner/agent profile exists.

DO \$\$
DECLARE
  owner_uid uuid;
  listing_uid uuid;
  seq int := 1;
  proj record;
  u int;
  is_rent boolean;
  price numeric;
  lat double precision;
  lng double precision;
  bed int;
  area numeric;
  title text;
  slug text;
BEGIN
  SELECT id INTO owner_uid FROM public.profiles
  WHERE role IN ('owner', 'agent', 'admin')
  ORDER BY created_at
  LIMIT 1;

  IF owner_uid IS NULL THEN
    RAISE NOTICE 'seed_listings: skipped — create a user with role owner/agent first';
    RETURN;
  END IF;

  IF EXISTS (SELECT 1 FROM public.listings WHERE listing_code LIKE 'LB-SEED-%' LIMIT 1) THEN
    RAISE NOTICE 'seed_listings: already present';
    RETURN;
  END IF;

''');

  var seq = 1;
  for (final p in projects) {
    final units = p['type'] == 'condo' ? 2 + rng.nextInt(2) : 1 + rng.nextInt(1);
    for (var u = 0; u < units; u++) {
      final isRent = rng.nextDouble() > 0.25;
      var price = isRent
          ? (12000 + rng.nextInt(45000)).toDouble()
          : (2500000 + rng.nextInt(12000000)).toDouble();
      if ((p['bts'] as String?)?.contains('อโศก') == true ||
          (p['bts'] as String?)?.contains('ทองหล่อ') == true) {
        price = isRent ? price * 1.12 : price * 1.08;
      }
      final lat = (p['lat'] as double) + (rng.nextDouble() - 0.5) * 0.004;
      final lng = (p['lng'] as double) + (rng.nextDouble() - 0.5) * 0.004;
      final bed = p['type'] == 'condo' ? rng.nextInt(3) : 2 + rng.nextInt(2);
      final area = p['type'] == 'condo'
          ? 28 + rng.nextInt(35)
          : 90 + rng.nextInt(80);
      final title = isRent
          ? '${bed == 0 ? 'สตูดิโอ' : '$bed นอน'} · ${p['name']}'
          : '${p['name']} ขาย';
      final slug = p['slug'] as String;

      buf.writeln('''
  INSERT INTO public.listings (
    listing_code, owner_id, created_by_id, listing_type, status, property_type,
    title, price_net, bedrooms, bathrooms, area_sqm, district, project_name,
    pet_allowed, listed_by_role, owner_verified, platform_has_owner_contact,
    co_agent_listing_type, location_public, published_at
  ) VALUES (
    'LB-SEED-${seq.toString().padLeft(4, '0')}',
    owner_uid, owner_uid,
    ${isRent ? "'rent'" : "'sale'"},
    'published', '${p['type']}',
    ${_q(title)},
    ${price.round()},
    $bed, 1, $area,
    ${_q(p['district'] as String)},
    ${_q(p['name'] as String)},
    ${rng.nextDouble() > 0.5},
    'owner', true, true,
    'co_agent_50_50',
    ST_SetSRID(ST_MakePoint($lng, $lat), 4326)::geography,
    now()
  ) RETURNING id INTO listing_uid;

  INSERT INTO public.listing_images (listing_id, storage_path, public_url, sort_order, moderation_status)
  VALUES
    (listing_uid, 'seed/$slug-$u-a', 'https://picsum.photos/seed/$slug-$u-a/800/600', 0, 'approved'),
    (listing_uid, 'seed/$slug-$u-b', 'https://picsum.photos/seed/$slug-$u-b/800/600', 1, 'approved'),
    (listing_uid, 'seed/$slug-$u-c', 'https://picsum.photos/seed/$slug-$u-c/800/600', 2, 'approved');
''');
      seq++;
    }
  }

  buf.writeln('''
  RAISE NOTICE 'seed_listings: inserted % listings', ${seq - 1};
END \$\$;
''');

  final out = File('supabase/seed_listings.sql');
  out.writeAsStringSync(buf.toString());
  stdout.writeln('Wrote ${out.path} (${seq - 1} listings)');
}

String _q(String s) => "'${s.replaceAll("'", "''")}'";

final _projects = [
  {'slug': 'true-thonglor', 'name': 'ทรู ทองหล่อ', 'district': 'วัฒนา', 'lat': 13.7242, 'lng': 100.5805, 'bts': 'BTS ทองหล่อ', 'type': 'condo'},
  {'slug': 'noble-remix-thonglor', 'name': 'โนเบิล รีมิกซ์ ทองหล่อ', 'district': 'วัฒนา', 'lat': 13.7265, 'lng': 100.5828, 'bts': 'BTS ทองหล่อ', 'type': 'condo'},
  {'slug': 'ashton-asoke', 'name': 'แอสตัน อโศก', 'district': 'วัฒนา', 'lat': 13.7395, 'lng': 100.5635, 'bts': 'BTS อโศก', 'type': 'condo'},
  {'slug': 'rhythm-sukhumvit-36', 'name': 'ริธึม สุขุมวิท 36', 'district': 'คลองเตย', 'lat': 13.7358, 'lng': 100.5712, 'bts': 'BTS ทองหล่อ', 'type': 'condo'},
  {'slug': 'the-lofts-ekkamai', 'name': 'เดอะ ลอฟท์ เอกมัย', 'district': 'วัฒนา', 'lat': 13.7285, 'lng': 100.5855, 'bts': 'BTS เอกมัย', 'type': 'condo'},
  {'slug': 'u-delight-bangna', 'name': 'ยู ดีไลท์ บางนา', 'district': 'บางนา', 'lat': 13.6682, 'lng': 100.6045, 'bts': 'BTS บางนา', 'type': 'condo'},
  {'slug': 'ideo-mobi-sukhumvit', 'name': 'ไอดีโอ โมบิ สุขุมวิท', 'district': 'พระโขนง', 'lat': 13.7025, 'lng': 100.6012, 'bts': 'BTS พระโขนง', 'type': 'condo'},
  {'slug': 'the-key-bts-wutthakat', 'name': 'เดอะ คีย์ BTS วุฒากาศ', 'district': 'บางบอน', 'lat': 13.7128, 'lng': 100.4565, 'bts': 'BTS วุฒากาศ', 'type': 'condo'},
  {'slug': 'life-rama-9', 'name': 'ไลฟ์ แอท รามา 9', 'district': 'ห้วยขวาง', 'lat': 13.7588, 'lng': 100.5652, 'bts': 'MRT พหลโยธิน', 'type': 'condo'},
  {'slug': 'aspire-sathorn', 'name': 'แอสไพร์ สาทร', 'district': 'สาทร', 'lat': 13.7185, 'lng': 100.5295, 'bts': 'BTS สุรศักดิ์', 'type': 'condo'},
  {'slug': 'the-address-sathorn', 'name': 'ดิ แอดเดรส สาทร', 'district': 'สาทร', 'lat': 13.7212, 'lng': 100.5318, 'bts': 'BTS สุรศักดิ์', 'type': 'condo'},
  {'slug': 'lumpini-place-rama3', 'name': 'ลุมพินี เพลส พระราม 3', 'district': 'ยานนาวา', 'lat': 13.6825, 'lng': 100.5388, 'bts': null, 'type': 'condo'},
  {'slug': 'magnolias-ratchadamri', 'name': 'แมกโนเลียส ราชดำริ', 'district': 'ปทุมวัน', 'lat': 13.7425, 'lng': 100.5395, 'bts': 'BTS ชิดลม', 'type': 'condo'},
  {'slug': 'the-line-sukhumvit-101', 'name': 'เดอะไลน์ สุขุมวิท 101', 'district': 'วัฒนา', 'lat': 13.6898, 'lng': 100.6072, 'bts': 'BTS บางจาก', 'type': 'condo'},
  {'slug': 'park-origin-thonglor', 'name': 'พาร์ค ออริจิ้น ทองหล่อ', 'district': 'วัฒนา', 'lat': 13.7318, 'lng': 100.5775, 'bts': 'BTS ทองหล่อ', 'type': 'condo'},
];
